### ISSUE TITLE
Indicate Pyramid supports both Python 2 and 3

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/trypyramid#10]
Per a discussion on [pylons-discuss](https://groups.google.com/forum/#!topic/pylons-discuss/IN9DJbYmo0E) the code sample and narrative imply that Pyramid supports only Python 3.

Perhaps we should add a remark in the code sample instructions that "Pyramid was the first Python web framework to support both Python 2 and 3"?

**Comment by mmerickel** [comment]
It's been a few years now, but cherrypy and bottle beat us to py3 as far as I can recall.

**Comment by pauleveritt** [comment]
I'll take this one and rephrase it.

**Comment by itd** [comment]
I might consider tweaking the wording then, such as:

Option:
Let's create a minimal web app in 5 minutes using Python (works as well in Python 2 as Python 3.)

Option:
Let's create a minimal web app in 5 minutes using Python (works great in Python 3 as as well legacy Python 2.6+ versions that may [be included | ship] with your OS.)

Option:
Put the info in parens above in a footnote(1).  ;-)

Just some ideas.

  -Kurt

**Comment by pauleveritt** [comment]
Sent a PR to Steve for some small wording change on this.

**Comment by stevepiercy** [comment]
See https://github.com/Pylons/tpc/pull/25.
