### ISSUE TITLE
Less UpperCase Everywhere

### ISSUE THREAD

**Issue by flibustenet** [Pylons/trypyramid#11]
I think it's not very readable to have too much upper case letters.
- The Start Small, Finish Big Stay Finished Framework
- Easy To Start
- When You Need Pyramid
- Supports Your Decisions
- By Artisans, For Artisans

If really needed, bold should be enough.
There is already enough upper case mandatory for Pyramid, Python.

**Comment by stevepiercy** [comment]
See the Chicago Manual of Style for headlines. These are correct in this context. The only one that might be changed is "Easy to Start", but ultimately that is a subjective decision. Here are a couple of references.
http://grammar.about.com/od/tz/g/Title-Case.htm
http://www.proofreadnow.com/blog/bid/38093/Headline-Style-Read-All-About-It

**Comment by flibustenet** [comment]
I didn't know, it's different in french

**Comment by tseaver** [comment]
@flibustenet thanks for caring about the site!
