### ISSUE TITLE
Support of ZODB

### ISSUE THREAD

**Issue by flibustenet** [Pylons/trypyramid#12]
ZODB support should be mentioned in "Supports Your Decisions". With traversal it's a killer feature of Pyramid.
Something like : 
Deep integration with ZODB when using traversal or classic url dispatch.

**Comment by stevepiercy** [comment]
We don't mention "URL dispatch" or "traversal" either. Those terms are common enough that they should be mentioned, too.

**Comment by pauleveritt** [comment]
I’m inclined to not mention traversal and definitely not ZODB on this page. It is aimed at audience for whom these things are hard to conceive and unlikely to do more than confuse.

We might consider it for subordinate pages.

—Paul

**Comment by ergo** [comment]
I agree.
URL dispatch is the more common solution people know - while traversal is a good selling point I wouldn't consider mentioning it at this stage. I also expect that people would think the entry barrier is higher than it really is.

**Comment by flibustenet** [comment]
Pyramid is for artisans isn't it ? ;-)
I'm agree that it's difficult to know if it will help (people who already like zodb) or the opposite...
I think i thought about zodb because with the term "Deep integration with SQLAlchemy" we can understand that SQLAlchemy will be to eat even if we don't need. However, it's a good selling point.

**Comment by ergo** [comment]
Maybe, but the target audience for this page might yet not be at that stage :-)

**Comment by tseaver** [comment]
ISTM that we shouldn't be implying (even by omission) that Pyramid only supports the patterns people expect (SQLAlchemy, URL dispatch) from other frameworks:  one of its key strengths is that it *doesn't* box you into only one pattern.

**Comment by ergo** [comment]
I would actually rephrase that as "Easy integration with sqlalchemy or ZODB" instead if we want to emphasise that there are multiple patterns supported.

**Comment by blaflamme** [comment]
Mongo and Redis are also easily supported so we could just talk about the data layer there and have links to patterns in the internal pages.

**Comment by chrisrossi** [comment]
The beauty of Pyramid is that it doesn't integrate with the ZODB.  It
doesn't integrate with SQLAlchemy.  It doesn't integrate with Mongo,
etc...  The beautiful part is that it doesn't have to.  Its abstractions
are clean enough, and its separation of concerns are well enough thought
out, that it doesn't need to.  Someone mentioned "deep integration" earlier
in this thread.  But the truth is that to the extent it integrates at all
it's very shallow integration.  Which is beautiful because that's all it
needs.  It just doesn't care.  You can use whatever you want and it's not
going to fight you over it.

Chris

**Comment by blaflamme** [comment]
BTW, this discussion should be transferred over tpc repo, this one is dead.

https://github.com/Pylons/tpc

**Comment by ergo** [comment]
soo err... pyramid site is being written in nodejs?

**Comment by ergo** [comment]
@chrisrossi Thats actually a good point, mabye the best option would be to emphasize that pyramid doesn't force any ORM or datastore but makes it trivial to use any of them.

**Comment by blaflamme** [comment]
@ergo it uses npm ecosystem for frontend tooling and dependencies. If we're going to need a backend we'll use pyramid for sure, probably as a service to feed the frontend app.

**Comment by pauleveritt** [comment]
> On May 17, 2015, at 1:26 PM, Tres Seaver <notifications@github.com> wrote:
> 
> ISTM that we shouldn't be implying (even by omission) that Pyramid only supports the patterns people expect (SQLAlchemy, URL dispatch) from other frameworks: one of its key strengths is that it doesn't box you into only one pattern.
> 
It's true, I threw the baby (db-agnostic) out with the bathwater (trying to ride coattails of SQLAlchemy.) How about something simple:

<li>Choose your database, with add-on support for
  <strong>SQLAlchemy</strong> and others</li>

—Paul

**Comment by stevepiercy** [comment]
```html
<li>Choose your database, with add-on support for
  <strong>SQLAlchemy</strong> and others</li>
```
works for me!
